require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/mentors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Mentor. As you add validations to Mentor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Mentor.create! valid_attributes
      get mentors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      mentor = Mentor.create! valid_attributes
      get mentor_url(mentor)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_mentor_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      mentor = Mentor.create! valid_attributes
      get edit_mentor_url(mentor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Mentor" do
        expect {
          post mentors_url, params: { mentor: valid_attributes }
        }.to change(Mentor, :count).by(1)
      end

      it "redirects to the created mentor" do
        post mentors_url, params: { mentor: valid_attributes }
        expect(response).to redirect_to(mentor_url(Mentor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Mentor" do
        expect {
          post mentors_url, params: { mentor: invalid_attributes }
        }.to change(Mentor, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post mentors_url, params: { mentor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested mentor" do
        mentor = Mentor.create! valid_attributes
        patch mentor_url(mentor), params: { mentor: new_attributes }
        mentor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the mentor" do
        mentor = Mentor.create! valid_attributes
        patch mentor_url(mentor), params: { mentor: new_attributes }
        mentor.reload
        expect(response).to redirect_to(mentor_url(mentor))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        mentor = Mentor.create! valid_attributes
        patch mentor_url(mentor), params: { mentor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested mentor" do
      mentor = Mentor.create! valid_attributes
      expect {
        delete mentor_url(mentor)
      }.to change(Mentor, :count).by(-1)
    end

    it "redirects to the mentors list" do
      mentor = Mentor.create! valid_attributes
      delete mentor_url(mentor)
      expect(response).to redirect_to(mentors_url)
    end
  end
end
